const s={token:localStorage.getItem("agentic.token"),sessionId:null,connectionId:null,workspaceId:null,repository:null,branch:null},$=x=>document.getElementById(x);
async function api(p,o={}){const r=await fetch(p,{...o,headers:{"Content-Type":"application/json",...(s.token?{Authorization:`Bearer ${s.token}`}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.message||b.error||"Request failed");return b}
function auth(reg=false){$("auth").classList.remove("hidden");$("app").classList.add("hidden");$("login").classList.toggle("hidden",reg);$("register").classList.toggle("hidden",!reg)}function showApp(){$("auth").classList.add("hidden");$("app").classList.remove("hidden")}
function render(m){const d=document.createElement("div");d.className=`msg ${m.role}`;d.textContent=m.content;$("messages").appendChild(d)}
async function openSession(id){const r=await api(`/api/agentic/sessions/${encodeURIComponent(id)}`);s.sessionId=r.session.id;$("messages").innerHTML="";(r.session.messages||[]).forEach(render);$("context").textContent=r.session.workspaceId?`workspace ${r.session.workspaceId}`:""}
async function sessions(){const r=await api("/api/agentic/sessions");$("sessions").innerHTML="";r.sessions.forEach(x=>{const row=document.createElement("div");row.className=`session-row ${x.id===s.sessionId?"selected":""}`;const b=document.createElement("button");b.className="session-main";b.textContent=x.title;b.onclick=()=>openSession(x.id);row.appendChild(b);const m=document.createElement("button");m.textContent="⋯";m.className="session-action";m.onclick=async()=>{const a=prompt("rename / archive / delete");if(a==="rename"){const t=prompt("Judul baru",x.title);if(t)await api(`/api/agentic/sessions/${x.id}`,{method:"PATCH",body:JSON.stringify({title:t})})}else if(a==="archive")await api(`/api/agentic/sessions/${x.id}`,{method:"PATCH",body:JSON.stringify({state:"archived"})});else if(a==="delete")await api(`/api/agentic/sessions/${x.id}`,{method:"DELETE"});await sessions()};row.appendChild(m);$("sessions").appendChild(row)})}
async function connections(){const r=await api("/api/agentic/connections");$("connections").innerHTML="";r.connections.forEach(c=>{const d=document.createElement("div");d.className=`card ${c.id===s.connectionId?"selected":""}`;d.textContent=`${c.name} · ${c.account?.login||""} · ${c.status}`;d.onclick=()=>{s.connectionId=c.id;loadRepos()};$("connections").appendChild(d)});if(s.connectionId)await loadRepos()}
async function loadRepos(){if(!s.connectionId)return;const r=await api(`/api/agentic/github/${encodeURIComponent(s.connectionId)}/repos`);$("repo").innerHTML="<option value=''>Select repository</option>";r.repositories.forEach(x=>{const o=document.createElement("option");o.value=x.fullName;o.textContent=x.fullName;$("repo").appendChild(o)});$("branch").disabled=true;$("bindWorkspace").disabled=true}
async function loadBranches(){const v=$("repo").value;if(!v)return;const [o,n]=v.split("/");const r=await api(`/api/agentic/github/${encodeURIComponent(s.connectionId)}/branches/${encodeURIComponent(o)}/${encodeURIComponent(n)}`);$("branch").innerHTML="<option value=''>Select branch</option>";r.branches.forEach(x=>{const o=document.createElement("option");o.value=x.name;o.textContent=x.name;$("branch").appendChild(o)});$("branch").disabled=false}
async function bindWorkspace(){const [owner,name]=s.repository.split("/");const r=await api("/api/agentic/workspaces",{method:"POST",body:JSON.stringify({name:s.repository,provider:"github",connectionId:s.connectionId,repository:{owner,name},branch:s.branch})});await renderWorkspace(r.workspace);await sessions()}
async function renderWorkspace(w){s.workspaceId=w.id;s.repository=w.repository.fullName;s.branch=w.branch;$("workspaceMeta").textContent=`${w.repository.fullName} · ${w.branch} · ${w.state}`;$("context").textContent=`${w.repository.fullName} @ ${w.branch}`;$("refreshWorkspace").disabled=false;await tree()}
async function loadWorkspace(){const r=await api("/api/agentic/workspaces");if(r.workspaces[0])await renderWorkspace(r.workspaces[0])}
async function tree(){if(!s.workspaceId)return;const r=await api(`/api/agentic/workspaces/${encodeURIComponent(s.workspaceId)}`),w=r.workspace,o=w.repository.owner,n=w.repository.name,t=await api(`/api/agentic/github/${encodeURIComponent(s.connectionId)}/tree/${encodeURIComponent(o)}/${encodeURIComponent(n)}?branch=${encodeURIComponent(w.branch)}`);$("tree").innerHTML="";t.tree.entries.filter(x=>x.type==="blob").slice(0,500).forEach(x=>{const b=document.createElement("button");b.className="file-row";b.textContent=x.path;b.onclick=()=>openFile(o,n,x.path,w.branch);$("tree").appendChild(b)})}
async function openFile(o,n,p,b){const r=await api(`/api/agentic/github/${encodeURIComponent(s.connectionId)}/file/${encodeURIComponent(o)}/${encodeURIComponent(n)}/${p.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(b)}`);$("file").textContent=r.file.content;await api(`/api/agentic/workspaces/${encodeURIComponent(s.workspaceId)}/current-file`,{method:"POST",body:JSON.stringify({file:p})})}
async function activity(){const r=await api("/api/agentic/activity");$("activity").innerHTML="";r.activity.slice(0,100).forEach(x=>{const d=document.createElement("div");d.className="card";d.textContent=`${x.action} · ${x.status} · ${x.label}`;$("activity").appendChild(d)})}
async function changes(){const q=s.workspaceId?`?workspaceId=${encodeURIComponent(s.workspaceId)}`:"";const r=await api(`/api/agentic/changes${q}`);$("changes").innerHTML="";if(!r.changes.length){$("changes").textContent="Belum ada Change.";return}r.changes.forEach(c=>{const d=document.createElement("article");d.className="card change-card";const h=document.createElement("strong");h.textContent=c.task;const m=document.createElement("p");m.textContent=`${c.status} · ${c.origin} · execution ${c.executionId||"—"}`;const f=document.createElement("pre");f.textContent=JSON.stringify({files:c.files,review:c.lastReview,history:c.history},null,2);d.append(h,m,f);$("changes").append(d)})}
function approvalText(value){try{return JSON.stringify(value||{},null,2)}catch{return "{}"}}
async function approvalAction(execution,action){const workPath=execution.workId?`/api/agentic/works/${encodeURIComponent(execution.workId)}`:null;try{if(action==="approve")await api(workPath?`${workPath}/approve`:`/api/agentic/executions/${encodeURIComponent(execution.id)}/approve`,{method:"POST",body:"{}"});else if(action==="reject")await api(`${workPath}/reject`,{method:"POST",body:JSON.stringify({reason:prompt("Alasan penolakan (opsional)")||"Approval ditolak oleh user"})});else if(action==="pause")await api(`${workPath}/pause`,{method:"POST",body:JSON.stringify({reason:"Dijeda dari approval surface"})});else if(action==="cancel")await api(workPath?`${workPath}/cancel`:`/api/agentic/executions/${encodeURIComponent(execution.id)}/cancel`,{method:"POST",body:JSON.stringify({reason:"Dibatalkan dari approval surface"})});else if(action==="revise"){const instruction=prompt("Instruksi revisi");if(!instruction)return;await api(`${workPath}/revise`,{method:"POST",body:JSON.stringify({instruction})})}else if(action==="resume")await api(`${workPath}/resume`,{method:"POST",body:"{}"});await approvals();await activity()}catch(error){alert(error.message)}}
function control(label,execution,action){const button=document.createElement("button");button.type="button";button.textContent=label;button.onclick=()=>approvalAction(execution,action);return button}
async function approvals(){const r=await api("/api/agentic/executions");const root=$("approvals");root.innerHTML="";const items=r.executions.filter(x=>x.approval||["waiting_approval","paused"].includes(x.status));if(!items.length){root.textContent="Tidak ada approval atau intervention yang menunggu.";return}items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).forEach(x=>{const a=x.approval||{},card=document.createElement("article"),head=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("p"),details=document.createElement("dl"),input=document.createElement("pre"),actions=document.createElement("div");card.className="card approval-card";head.className="approval-head";title.textContent=`${a.status==="pending"?"Approval diperlukan":"Intervensi execution"} · ${a.tool||x.status}`;meta.textContent=a.reason||`Execution ${x.status}`;details.innerHTML=`<dt>Risiko</dt><dd>${a.risk||"—"}</dd><dt>Capability</dt><dd>${a.requestedCapability||"—"}</dd><dt>Resource</dt><dd>${a.affectedResource||"—"}</dd><dt>Kedaluwarsa</dt><dd>${a.expiresAt||"—"}</dd>`;input.textContent=approvalText(a.input);actions.className="approval-actions";if(a.status==="pending"&&x.status==="waiting_approval"){actions.append(control("Approve",x,"approve"),control("Reject",x,"reject"),control("Pause",x,"pause"),control("Revise instruction",x,"revise"),control("Cancel",x,"cancel"))}else if(x.workId&&x.status==="paused"){actions.append(control("Resume same execution",x,"resume"),control("Revise instruction",x,"revise"),control("Cancel",x,"cancel"))}head.append(title,meta);card.append(head,details,input,actions);root.appendChild(card)})}
$("repo").onchange=async()=>{s.repository=$("repo").value;if(s.repository)await loadBranches()};$("branch").onchange=()=>{s.branch=$("branch").value;$("bindWorkspace").disabled=!s.branch};$("bindWorkspace").onclick=async()=>{try{await bindWorkspace()}catch(e){alert(e.message)}};$("refreshWorkspace").onclick=async()=>{try{const r=await api(`/api/agentic/workspaces/${encodeURIComponent(s.workspaceId)}/refresh`,{method:"POST"});await renderWorkspace(r.workspace)}catch(e){alert(e.message)}};
$("login").onsubmit=async e=>{e.preventDefault();try{const r=await api("/api/agentic/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});s.token=r.token;localStorage.setItem("agentic.token",s.token);await boot()}catch(x){alert(x.message)}};$("register").onsubmit=async e=>{e.preventDefault();try{await api("/api/agentic/auth/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("regEmail").value,password:$("regPassword").value})});auth(false);$("email").value=$("regEmail").value}catch(x){alert(x.message)}};$("registerMode").onclick=()=>auth(true);$("loginMode").onclick=()=>auth(false);
$("newChat").onclick=async()=>{const r=await api("/api/agentic/sessions",{method:"POST",body:"{}"});await openSession(r.session.id);await sessions()};$("chat").onsubmit=async e=>{e.preventDefault();const p=$("prompt").value.trim();if(!p||!s.sessionId)return;$("prompt").value="";try{const r=await api("/api/agentic/chat",{method:"POST",body:JSON.stringify({sessionId:s.sessionId,prompt:p})});if(r.message)render(r.message);await sessions();await activity()}catch(x){alert(x.message)}};
$("github").onsubmit=async e=>{e.preventDefault();try{await api("/api/agentic/connections/github",{method:"POST",body:JSON.stringify({token:$("githubToken").value,name:$("githubName").value||"GitHub"})});$("githubToken").value="";await connections()}catch(x){alert(x.message)}};$("logout").onclick=async()=>{await api("/api/agentic/auth/logout",{method:"POST"}).catch(()=>{});s.token=null;s.sessionId=null;s.workspaceId=null;localStorage.removeItem("agentic.token");auth(false)};
$("refreshApprovals").onclick=()=>approvals().catch(e=>alert(e.message));$("refreshChanges").onclick=()=>changes().catch(e=>alert(e.message));document.querySelectorAll("[data-view]").forEach(b=>b.onclick=async()=>{["chat","approvals","connections","files","activity","changes"].forEach(v=>$(`${v}View`).classList.add("hidden"));$(`${b.dataset.view}View`).classList.remove("hidden");if(b.dataset.view==="approvals")await approvals();if(b.dataset.view==="connections")await connections();if(b.dataset.view==="files"){await connections();await loadWorkspace()}if(b.dataset.view==="activity")await activity();if(b.dataset.view==="changes")await changes()});$("menu").onclick=()=>document.querySelector("aside").classList.toggle("open");
async function boot(){if(!s.token)return auth(false);try{const r=await api("/api/agentic/me");$("user").textContent=r.user.email;showApp();await sessions();await connections();await activity();await approvals()}catch{localStorage.removeItem("agentic.token");s.token=null;auth(false)}}boot();
