const s={token:localStorage.getItem("agentic.token"),sessionId:null,connectionId:null},$=x=>document.getElementById(x);
async function api(p,o={}){const r=await fetch(p,{...o,headers:{"Content-Type":"application/json",...(s.token?{Authorization:`Bearer ${s.token}`}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.message||b.error||"Request failed");return b}
function auth(reg=false){$("auth").classList.remove("hidden");$("app").classList.add("hidden");$("login").classList.toggle("hidden",reg);$("register").classList.toggle("hidden",!reg)}function showApp(){$("auth").classList.add("hidden");$("app").classList.remove("hidden")}
function render(m){const d=document.createElement("div");d.className=`msg ${m.role}`;d.textContent=m.content;$("messages").appendChild(d)}
async function openSession(id){const r=await api(`/api/agentic/sessions/${encodeURIComponent(id)}`);s.sessionId=r.session.id;$("messages").innerHTML="";(r.session.messages||[]).forEach(render);$("context").textContent=r.session.state==="archived"?"Archived session":""}
async function sessions(){const r=await api("/api/agentic/sessions");$("sessions").innerHTML="";r.sessions.forEach(x=>{const row=document.createElement("div");row.className=`session-row ${x.id===s.sessionId?"selected":""}`;const b=document.createElement("button");b.className="session-main";b.textContent=x.title;b.onclick=()=>openSession(x.id);row.appendChild(b);const m=document.createElement("button");m.textContent="⋯";m.className="session-action";m.onclick=async()=>{const a=prompt("rename / archive / delete");if(a==="rename"){const t=prompt("Judul baru",x.title);if(t)await api(`/api/agentic/sessions/${x.id}`,{method:"PATCH",body:JSON.stringify({title:t})})}else if(a==="archive")await api(`/api/agentic/sessions/${x.id}`,{method:"PATCH",body:JSON.stringify({state:"archived"})});else if(a==="delete")await api(`/api/agentic/sessions/${x.id}`,{method:"DELETE"});await sessions()};row.appendChild(m);$("sessions").appendChild(row)})}
async function connections(){const r=await api("/api/agentic/connections");$("connections").innerHTML="";r.connections.forEach(c=>{const d=document.createElement("div");d.className="card";d.textContent=`${c.name} · ${c.account?.login||""} · ${c.status}`;d.onclick=()=>{s.connectionId=c.id;repos()};$("connections").appendChild(d)})}
async function repos(){if(!s.connectionId)return;const r=await api(`/api/agentic/github/${s.connectionId}/repos`),sel=document.createElement("select");sel.innerHTML="<option value=''>Select repository</option>";r.repositories.forEach(x=>{const o=document.createElement("option");o.value=x.fullName;o.textContent=x.fullName;sel.appendChild(o)});sel.onchange=async()=>{if(!sel.value)return;const [o,n]=sel.value.split("/"),t=await api(`/api/agentic/github/${s.connectionId}/tree/${encodeURIComponent(o)}/${encodeURIComponent(n)}`),f=t.tree.entries.find(x=>x.type==="blob");if(f){const x=await api(`/api/agentic/github/${s.connectionId}/file/${encodeURIComponent(o)}/${encodeURIComponent(n)}/${f.path}`);$("file").textContent=x.file.content}};$("repos").replaceChildren(sel)}
$("login").onsubmit=async e=>{e.preventDefault();try{const r=await api("/api/agentic/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("password").value})});s.token=r.token;localStorage.setItem("agentic.token",s.token);await boot()}catch(x){alert(x.message)}};
$("register").onsubmit=async e=>{e.preventDefault();try{await api("/api/agentic/auth/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("regEmail").value,password:$("regPassword").value})});auth(false);$("email").value=$("regEmail").value}catch(x){alert(x.message)}};
$("registerMode").onclick=()=>auth(true);$("loginMode").onclick=()=>auth(false);$("newChat").onclick=async()=>{const r=await api("/api/agentic/sessions",{method:"POST",body:"{}"});await openSession(r.session.id);await sessions()};
$("chat").onsubmit=async e=>{e.preventDefault();const p=$("prompt").value.trim();if(!p||!s.sessionId)return;$("prompt").value="";try{const r=await api("/api/agentic/chat",{method:"POST",body:JSON.stringify({sessionId:s.sessionId,prompt:p})});if(r.message)render(r.message);await sessions()}catch(x){alert(x.message)}};
$("github").onsubmit=async e=>{e.preventDefault();try{await api("/api/agentic/connections/github",{method:"POST",body:JSON.stringify({token:$("githubToken").value,name:$("githubName").value||"GitHub"})});$("githubToken").value="";await connections()}catch(x){alert(x.message)}};
$("logout").onclick=async()=>{await api("/api/agentic/auth/logout",{method:"POST"}).catch(()=>{});s.token=null;s.sessionId=null;localStorage.removeItem("agentic.token");auth(false)};document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{["chat","connections","files"].forEach(v=>$(`${v}View`).classList.add("hidden"));$(`${b.dataset.view}View`).classList.remove("hidden");if(b.dataset.view==="connections")connections();if(b.dataset.view==="files")repos()});$("menu").onclick=()=>document.querySelector("aside").classList.toggle("open");
async function boot(){if(!s.token)return auth(false);try{const r=await api("/api/agentic/me");$("user").textContent=r.user.email;showApp();await sessions();if(s.sessionId)await openSession(s.sessionId);await connections()}catch{localStorage.removeItem("agentic.token");s.token=null;auth(false)}}boot();
