import { createAgenticStore } from "./store.js";
import { createAuthService } from "./auth.js";
import { createGitHubService } from "./github.js";
import { createId } from "./ids.js";
import { AgenticError } from "./errors.js";
import { runAgent,extractMemoryCandidates,addMemories,retrieveMemories,resolveMemoryConflicts,getActiveMemories } from "../../../core/agent-engine/index.js";
import { auditEvent } from "../../../core/security/index.js";
export function createAgenticApplication({storage=undefined}={}){const store=createAgenticStore({storage}),auth=createAuthService({store}),github=createGitHubService({store});
 async function createChatSession(u,{title="New Chat",connectionId=null,workspaceId=null}={}){const s={id:createId("chat"),title:String(title||"New Chat").trim().slice(0,160),connectionId,workspaceId,messages:[],memories:[],taskId:null,executionId:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await store.putChatSession(u,s);return s;}
 async function getSession(u,id){if(id){const s=await store.getChatSession(u,id);if(!s)throw new AgenticError("SESSION_NOT_FOUND","Chat session tidak ditemukan",404);return s;}return createChatSession(u,{});}
 async function chat(u,{sessionId,prompt,provider,model,approvalToken=null}={}){if(typeof prompt!=="string"||!prompt.trim())throw new AgenticError("INVALID_PROMPT","Prompt wajib diisi");const s=await getSession(u,sessionId);const conversation=s.messages.slice(-20).map(m=>({role:m.role,content:m.content}));const user={id:createId("msg"),role:"user",content:prompt.trim().slice(0,12000),createdAt:new Date().toISOString()};s.messages.push(user);const result=await runAgent({prompt:user.content,provider,model,conversation,memories:getActiveMemories(s.memories),sessionId:`${u}:${s.id}`,approvalToken,principal:{userId:u},applicationId:"agentic"});const assistant={id:createId("msg"),role:"assistant",content:String(result.text||""),createdAt:new Date().toISOString(),executionId:result.execution?.id||null};s.messages.push(assistant);s.messages=s.messages.slice(-40);addMemories(s.memories,extractMemoryCandidates(user.content));resolveMemoryConflicts(s.memories);s.executionId=result.execution?.id||null;s.updatedAt=new Date().toISOString();await store.putChatSession(u,s);auditEvent({actor:"user",action:"agentic-chat",outcome:"completed",principal:{userId:u},sessionId:s.id,applicationId:"agentic",executionId:result.execution?.id||null});return {sessionId:s.id,message:assistant,execution:result.execution||null,plan:result.plan||null,memory:{active:getActiveMemories(s.memories).length,relevant:retrieveMemories(s.memories,user.content).length}};}
 async function createWorkspace(u,input){const w={id:createId("workspace"),provider:input.provider,connectionId:input.connectionId,resource:input.resource,branch:input.branch||null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await store.putWorkspace(u,w);return w;}
 return Object.freeze({store,auth,github,createChatSession,chat,createWorkspace,listSessions:u=>store.listChatSessions(u),listConnections:u=>store.listConnections(u),listWorkspaces:u=>store.listWorkspaces(u),listTasks:u=>store.listTasks(u),listActivities:u=>store.listActivities(u)});}
