import { createAgenticStore } from "./store.js";
import { createAuthService } from "./auth.js";
import { createConnectionService } from "./connections.js";
import { createWorkspaceService } from "./workspaces.js";
import { createGitHubService } from "./github.js";
import { createWorkService } from "./work.js";
import { createWorkExecutionService } from "./work-execution.js";
import { createId } from "./ids.js";
import { createRecoveryService } from "./recovery.js";
import { createRealtimeService } from "./realtime.js";
import { AgenticError } from "./errors.js";
import { runAgent,createPlan,extractMemoryCandidates,addMemories,retrieveMemories,resolveMemoryConflicts,getActiveMemories } from "../../../core/agent-engine/index.js";
import { createExecutionId } from "../../../core/agent-engine/reliability/runtime.js";
import { issueApproval,auditEvent } from "../../../core/security/index.js";
const TERMINAL=new Set(["completed","failed","cancelled","stopped","max_turns"]);
const title=v=>String(v??"").trim().slice(0,160)||"New Chat";
function resultStatus(r){if(r?.execution?.status==="failed")return"failed";if(r?.execution?.status==="cancelled")return"cancelled";if(r?.approval?.required||r?.status==="waiting_approval")return"waiting_approval";if(r?.autonomy?.status==="stopped"||/Execution dihentikan secara bounded/i.test(String(r?.text||"")))return"stopped";if(/mencapai batas maksimum/i.test(String(r?.text||"")))return"max_turns";return"completed"}
function approvalCandidate(r){const x=r?.tool?.steps?.at(-1);return x?.result?.requiresApproval?{tool:x.name,input:x.input||{},reason:x.result.error||"Tool memerlukan human approval"}:null}
export function createAgenticApplication({storage,agentRunner=runAgent,workPlanner=createPlan}={}){
  const store=createAgenticStore({storage}),auth=createAuthService({store}),connections=createConnectionService({store}),github=createGitHubService({store,connections}),realtime=createRealtimeService({store}),recovery=createRecoveryService({store});
  connections.registerProvider("github",{validate:github.validateConnection,health:github.healthConnection});
  const workspaces=createWorkspaceService({store,connections});
  workspaces.registerProvider("github",{repositoryContext:github.repositoryContext});
  const work=createWorkService({
    store,
    tasks:{get:async(u,id)=>{const task=await store.getTask(u,id);if(!task)throw new AgenticError("TASK_NOT_FOUND","Task tidak ditemukan",404);return task;}},
    executions:{get:async(u,id)=>{const execution=await store.getExecution(u,id);if(!execution)throw new AgenticError("EXECUTION_NOT_FOUND","Execution tidak ditemukan",404);return execution;}}
  });
  const workExecution=createWorkExecutionService({store,work,realtime,agentRunner,planner:workPlanner,approvalAuthority:issueApproval});
  async function messages(u,sid,{limit=100,before=null}={}){const s=await store.getChatSession(u,sid);if(!s)throw new AgenticError("SESSION_NOT_FOUND","Chat session tidak ditemukan",404);let a=(await store.listChatMessages(u)).filter(x=>x.sessionId===sid).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)));if(before)a=a.filter(x=>x.createdAt<before);const n=Math.max(1,Math.min(Number(limit)||100,100)),page=a.slice(-n);if(!page.length&&s.messages?.length)return{messages:s.messages.slice(-n),nextBefore:null,total:s.messages.length};return{messages:page,nextBefore:page.length===n?page[0].createdAt:null,total:a.length}}
  async function session(u,id){const s=await store.getChatSession(u,id);if(!s)throw new AgenticError("SESSION_NOT_FOUND","Chat session tidak ditemukan",404);s.messages=(await messages(u,id)).messages;return s}
  async function active(u,id){const s=await store.getChatSession(u,id);if(!s)throw new AgenticError("SESSION_NOT_FOUND","Chat session tidak ditemukan",404);if(s.state==="archived")throw new AgenticError("SESSION_ARCHIVED","Chat session diarsipkan; restore terlebih dahulu",409);if(s.state==="deleted")throw new AgenticError("SESSION_DELETED","Chat session sudah dihapus",409);return s}
  async function patch(u,id,p){const s=await store.getChatSession(u,id);if(!s)throw new AgenticError("SESSION_NOT_FOUND","Chat session tidak ditemukan",404);const n={...s,...p,id:s.id,ownerId:u,updatedAt:new Date().toISOString()};await store.putChatSession(u,n,{expectedVersion:s._storage?.version});return n}
  async function createChatSession(u,o={}){const now=new Date().toISOString(),s={id:createId("chat"),title:title(o.title),state:"active",connectionId:o.connectionId||null,workspaceId:o.workspaceId||null,messages:[],memories:[],taskId:null,executionId:null,createdAt:now,updatedAt:now,archivedAt:null,deletedAt:null,lastMessageAt:null};await store.putChatSession(u,s);return s}
  async function addMessage(u,sid,m){const x={id:m.id||createId("msg"),sessionId:sid,role:m.role,content:String(m.content||"").slice(0,12000),createdAt:m.createdAt||new Date().toISOString(),executionId:m.executionId||null};await store.putChatMessage(u,x,{overwrite:false});const s=await store.getChatSession(u,sid);await patch(u,sid,{messages:[...(s.messages||[]),x].slice(-40),lastMessageAt:x.createdAt});return x}
  async function activity(u,eid,sid,e){const x={id:e.id||createId("activity"),executionId:eid,sessionId:sid,type:e.type||"activity",action:e.action||"unknown",status:e.status||"running",label:String(e.label||e.action||"Activity").slice(0,300),meta:e.meta||{},error:e.error||null,createdAt:new Date().toISOString()};await store.putActivity(u,x);await realtime.publish(u,x);return x}
  async function createExecution(u,sid,p){const now=new Date().toISOString(),t={id:createId("task"),sessionId:sid,status:"running",title:String(p).slice(0,160),createdAt:now,updatedAt:now},e={id:createExecutionId(),sessionId:sid,taskId:t.id,status:"running",prompt:String(p).slice(0,12000),plan:null,currentStep:null,checkpoint:null,approval:null,result:null,error:null,startedAt:now,updatedAt:now,finishedAt:null};await store.putTask(u,t);await store.putExecution(u,e);return e}
  async function exec(u,id,p={}){const e=await store.getExecution(u,id);if(!e)throw new AgenticError("EXECUTION_NOT_FOUND","Execution tidak ditemukan",404);const n={...e,...p,id:e.id,ownerId:u,updatedAt:new Date().toISOString()};await store.putExecution(u,n,{expectedVersion:e._storage?.version});if(TERMINAL.has(n.status)&&e.taskId){const t=await store.getTask(u,e.taskId);if(t)await store.putTask(u,{...t,status:n.status,updatedAt:n.updatedAt})}return n}
  async function runExecution(u,s,p,o={}){const e=o.resumeExecutionId?await execActive(u,o.resumeExecutionId):await createExecution(u,s.id,p);await patch(u,s.id,{taskId:e.taskId,executionId:e.id});const emit=async ev=>{const cur=await store.getExecution(u,e.id);if(cur?.status==="cancelled")throw new AgenticError("EXECUTION_CANCELLED","Execution dibatalkan",409);await activity(u,e.id,s.id,ev);if(ev.action==="planning"&&ev.status==="completed")await exec(u,e.id,{plan:ev.meta||null});if(ev.action==="checkpoint")await exec(u,e.id,{checkpoint:ev.meta||null})};try{const r=await agentRunner({prompt:p,provider:o.provider,model:o.model,conversation:(await messages(u,s.id,{limit:20})).messages.map(m=>({role:m.role,content:m.content})),memories:getActiveMemories(s.memories||[]),sessionId:`${u}:${s.id}`,approvalToken:o.approvalToken||null,principal:{userId:u},applicationId:"agentic",executionId:o.resumeExecutionId||undefined,agentExecutionId:e.id,onActivity:emit});const c=approvalCandidate(r);if(c&&!o.approvalToken){const a=issueApproval({tool:c.tool,input:c.input,sessionId:`${u}:${s.id}`,reason:c.reason});const f=await exec(u,e.id,{status:"waiting_approval",approval:{tool:c.tool,input:c.input,reason:c.reason,expiresAt:a.expiresAt},result:null});await activity(u,e.id,s.id,{action:"approval_required",status:"waiting",label:`Approval diperlukan · ${c.tool}`,meta:{tool:c.tool,expiresAt:a.expiresAt}});return{sessionId:s.id,execution:f,plan:r.plan||null,approvalRequired:true}}const st=resultStatus(r),f=await exec(u,e.id,{status:st,result:r.text||null,plan:r.plan||null,finishedAt:TERMINAL.has(st)?new Date().toISOString():null});await activity(u,e.id,s.id,{action:"execution",status:st==="completed"?"completed":"finished",label:st==="completed"?"Pekerjaan selesai":`Execution selesai · ${st}`,meta:{status:st}});return{result:r,execution:f}}catch(err){const st=err?.code==="EXECUTION_CANCELLED"?"cancelled":"failed",f=await exec(u,e.id,{status:st,error:err?.message||String(err),finishedAt:new Date().toISOString()});if(st==="cancelled")return{result:{text:"Execution dibatalkan."},execution:f};throw err}}
  async function resumeExecution(u,id){const e=await recovery.get(u,id);await recovery.markResuming(u,id);return runExecution(u,await active(u,e.sessionId),e.prompt,{resumeExecutionId:id});}
  async function execActive(u,id){const e=await store.getExecution(u,id);if(!e)throw new AgenticError("EXECUTION_NOT_FOUND","Execution tidak ditemukan",404);if(e.status==="cancelled")throw new AgenticError("EXECUTION_CANCELLED","Execution dibatalkan",409);return e}
  async function chat(u,{sessionId,prompt,provider,model,approvalToken=null}={}){if(!String(prompt||"").trim())throw new AgenticError("INVALID_PROMPT","Prompt wajib diisi");const s=await active(u,sessionId),user=await addMessage(u,s.id,{role:"user",content:prompt.trim()}),run=await runExecution(u,s,user.content,{provider,model,approvalToken});if(run.approvalRequired)return run;const assistant=await addMessage(u,s.id,{role:"assistant",content:String(run.result.text||""),executionId:run.execution.id});const latest=await store.getChatSession(u,s.id);addMemories(latest.memories||[],extractMemoryCandidates(user.content));resolveMemoryConflicts(latest.memories||[]);await store.putChatSession(u,{...latest,updatedAt:new Date().toISOString()},{expectedVersion:latest._storage?.version});auditEvent({actor:"user",action:"agentic-chat",outcome:run.execution.status,principal:{userId:u},sessionId:s.id,applicationId:"agentic",executionId:run.execution.id});return{sessionId:s.id,message:assistant,execution:run.execution,plan:run.result.plan||null,memory:{active:getActiveMemories(latest.memories||[]).length,relevant:retrieveMemories(latest.memories||[],user.content).length}}}
  async function rename(u,id,t){await active(u,id);return patch(u,id,{title:title(t)})}async function archive(u,id){const s=await session(u,id);if(s.state==="deleted")throw new AgenticError("SESSION_DELETED","Chat session sudah dihapus",409);return patch(u,id,{state:"archived",archivedAt:new Date().toISOString()})}async function restore(u,id){const s=await session(u,id);return patch(u,id,{state:"active",archivedAt:null,deletedAt:null})}async function remove(u,id){const s=await session(u,id);if(s.state!=="deleted")return patch(u,id,{state:"deleted",deletedAt:new Date().toISOString()});return s}
  async function approve(u,id){const e=await execActive(u,id);if(e.status!=="waiting_approval"||!e.approval)throw new AgenticError("APPROVAL_NOT_PENDING","Execution tidak sedang menunggu approval",409);if(e.approval.expiresAt&&Date.parse(e.approval.expiresAt)<=Date.now())throw new AgenticError("APPROVAL_EXPIRED","Approval sudah kedaluwarsa",409);const a=issueApproval({tool:e.approval.tool,input:e.approval.input,sessionId:`${u}:${e.sessionId}`,reason:e.approval.reason});await exec(u,id,{status:"running",approval:null});return runExecution(u,await active(u,e.sessionId),e.prompt,{approvalToken:a.token,resumeExecutionId:id})}
  async function cancel(u,id){const e=await execActive(u,id);if(TERMINAL.has(e.status))return e;return exec(u,id,{status:"cancelled",finishedAt:new Date().toISOString(),error:"Execution dibatalkan oleh user"})}
  async function listSessions(u,o={}){let a=await store.listChatSessions(u);a=a.filter(s=>o.deleted?s.state!==undefined:s.state!=="deleted").filter(s=>o.archived===false?s.state==="active":true);return a.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(({messages,...s})=>({...s,messageCount:messages?.length||0}))}
  return Object.freeze({store,auth,connections,workspaces,github,work,workExecution,realtime,recovery,createChatSession,session,sessionMessages:messages,listSessions,renameSession:rename,archiveSession:archive,restoreSession:restore,deleteSession:remove,chat,approveExecution:approve,cancelExecution:cancel,resumeExecution,createWork:work.create,getWork:work.get,listWorks:work.list,updateWork:work.update,transitionWork:work.transition,planWork:workExecution.plan,runWork:workExecution.run,pauseWork:workExecution.pause,stopWork:workExecution.stop,cancelWork:workExecution.cancel,listWorkActivities:workExecution.listActivities,attachWorkTask:work.attachTask,attachWorkExecution:work.attachExecution,attachWorkReference:work.attachReference,listConnections:u=>connections.list(u),listWorkspaces:u=>workspaces.list(u),listExecutions:u=>store.listExecutions(u),listTasks:u=>store.listTasks(u),listActivities:u=>store.listActivities(u),getExecution:async(u,id)=>{const e=await store.getExecution(u,id);if(!e)throw new AgenticError("EXECUTION_NOT_FOUND","Execution tidak ditemukan",404);return e}})}
