import { createId } from "./ids.js";
import { hashPassword, verifyPassword } from "./crypto.js";
import { AgenticError } from "./errors.js";
const TOKEN_TTL_MS=Number(process.env.AGENTIC_AUTH_TTL_MS||7*24*60*60*1000);
export function createAuthService({store}){async function register({email,password,name=""}={}){const e=String(email||"").trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e))throw new AgenticError("INVALID_EMAIL","Email tidak valid");if((await store.listUsers()).some(u=>u.email===e))throw new AgenticError("EMAIL_EXISTS","Email sudah terdaftar",409);const u={id:createId("user"),email:e,name:String(name||"").trim().slice(0,120),passwordHash:hashPassword(password),createdAt:new Date().toISOString()};await store.createUser(u);return sanitizeUser(u);}
 async function login({email,password}={}){const e=String(email||"").trim().toLowerCase();const u=(await store.listUsers()).find(x=>x.email===e);if(!u||!verifyPassword(password,u.passwordHash))throw new AgenticError("INVALID_CREDENTIALS","Email atau password salah",401);const s={id:createId("auth"),userId:u.id,createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+TOKEN_TTL_MS).toISOString(),revokedAt:null};await store.putAuthSession(s);return {token:s.id,user:sanitizeUser(u),expiresAt:s.expiresAt};}
 async function authenticate(token){const s=await store.getAuthSession(token);if(!s||s.revokedAt||Date.parse(s.expiresAt)<=Date.now())throw new AgenticError("UNAUTHENTICATED","Authentication diperlukan",401);const u=await store.getUser(s.userId);if(!u)throw new AgenticError("UNAUTHENTICATED","User tidak ditemukan",401);return {session:s,user:sanitizeUser(u)};}
 async function logout(token){const s=await store.getAuthSession(token);if(!s)return;s.revokedAt=new Date().toISOString();await store.state.put("auth-sessions",s.id,s,{expectedVersion:s._storage?.version});}
 function sanitizeUser(u){return {id:u.id,email:u.email,name:u.name,createdAt:u.createdAt};} return Object.freeze({register,login,authenticate,logout,sanitizeUser});}
