import { encryptSecret, decryptSecret } from "./crypto.js";
import { createId } from "./ids.js";
import { AgenticError } from "./errors.js";
const API="https://api.github.com";
async function request(token,path){const r=await fetch(`${API}${path}`,{headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28"}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new AgenticError(r.status===401?"GITHUB_AUTH_FAILED":"GITHUB_REQUEST_FAILED",body?.message||`GitHub request failed (${r.status})`,r.status===401?401:502,{rateLimitRemaining:r.headers.get("x-ratelimit-remaining")});return body;}
export function createGitHubService({store}){async function tokenFor(u,id){const c=await store.getConnection(u,id);if(!c||c.provider!=="github")throw new AgenticError("CONNECTION_NOT_FOUND","GitHub connection tidak ditemukan",404);if(c.status!=="active")throw new AgenticError("CONNECTION_INACTIVE","GitHub connection tidak aktif",409);return {connection:c,token:decryptSecret(c.credential)};}
 async function connect(u,{token,name="GitHub"}={}){if(typeof token!=="string"||token.length<10)throw new AgenticError("INVALID_GITHUB_TOKEN","GitHub token tidak valid");const account=await request(token,"/user");const c={id:createId("conn"),provider:"github",name:String(name).trim().slice(0,120)||"GitHub",account:{login:account.login,id:account.id,avatarUrl:account.avatar_url||null},credential:encryptSecret(token),status:"active",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await store.putConnection(u,c);return publicConnection(c);}
 async function repositories(u,id){const {token}=await tokenFor(u,id);return (await request(token,"/user/repos?per_page=100&sort=updated")).map(r=>({id:r.id,name:r.name,fullName:r.full_name,private:r.private,defaultBranch:r.default_branch,htmlUrl:r.html_url,description:r.description}));}
 async function branches(u,id,o,r){const {token}=await tokenFor(u,id);return (await request(token,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/branches?per_page=100`)).map(b=>({name:b.name,sha:b.commit?.sha||null}));}
 async function tree(u,id,o,r,branch=null){const {token}=await tokenFor(u,id);const body=await request(token,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/git/trees/${branch?encodeURIComponent(branch):"HEAD"}?recursive=1`);return {sha:body.sha,truncated:Boolean(body.truncated),entries:(body.tree||[]).map(x=>({path:x.path,type:x.type,size:x.size||0,sha:x.sha}))};}
 async function file(u,id,o,r,p,ref=null){const {token}=await tokenFor(u,id);const suffix=ref?`?ref=${encodeURIComponent(ref)}`:"";const body=await request(token,`/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/contents/${String(p).split("/").map(encodeURIComponent).join("/")}${suffix}`);if(!body||Array.isArray(body)||body.type!=="file")throw new AgenticError("GITHUB_FILE_NOT_FOUND","Resource bukan file",404);return {path:body.path,sha:body.sha,size:body.size,content:body.encoding==="base64"?Buffer.from(body.content.replace(/\s+/g,""),"base64").toString("utf8"):String(body.content||"")};}
 function publicConnection(c){return {id:c.id,provider:c.provider,name:c.name,account:c.account,status:c.status,createdAt:c.createdAt,updatedAt:c.updatedAt};} return Object.freeze({connect,repositories,branches,tree,file,publicConnection});}
