import express from "express";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {createAgenticApplication} from "./application.js";
import {normalizeAgenticError} from "./errors.js";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../frontend");
const bearer=req=>String(req.headers.authorization||"").startsWith("Bearer ")?String(req.headers.authorization).slice(7).trim():"";
export function createAgenticServer({application=createAgenticApplication(),configuration={}}={}){const app=express();app.use(express.json({limit:configuration.requestBodyLimit||"1mb"}));app.use(express.static(root));
 const sendError=(r,e)=>{const x=normalizeAgenticError(e);return r.status(x.status).json({ok:false,error:x.code,message:x.message,details:x.details||undefined})};
 app.get("/api/agentic/health",(_q,r)=>r.json({ok:true,application:"agentic",version:"v3"}));
 app.post("/api/agentic/auth/register",async(q,r)=>{try{r.status(201).json({ok:true,user:await application.auth.register(q.body||{})})}catch(e){sendError(r,e)}});
 app.post("/api/agentic/auth/login",async(q,r)=>{try{r.json({ok:true,...await application.auth.login(q.body||{})})}catch(e){sendError(r,e)}});
 app.post("/api/agentic/auth/logout",async(q,r)=>{try{await application.auth.logout(bearer(q));r.json({ok:true})}catch(e){sendError(r,e)}});
 app.use("/api/agentic",async(q,r,n)=>{try{q.agentic=await application.auth.authenticate(bearer(q));n()}catch(e){sendError(r,e)}});
 app.get("/api/agentic/me",(q,r)=>r.json({ok:true,user:q.agentic.user}));
 app.get("/api/agentic/sessions",async(q,r)=>r.json({ok:true,sessions:await application.listSessions(q.agentic.user.id)}));
 app.post("/api/agentic/sessions",async(q,r)=>{try{r.status(201).json({ok:true,session:await application.createChatSession(q.agentic.user.id,q.body||{})})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/connections",async(q,r)=>r.json({ok:true,connections:await application.listConnections(q.agentic.user.id)}));
 app.post("/api/agentic/connections/github",async(q,r)=>{try{r.status(201).json({ok:true,connection:await application.github.connect(q.agentic.user.id,q.body||{})})}catch(e){sendError(r,e)}});
 app.delete("/api/agentic/connections/:id",async(q,r)=>{try{if(!await application.store.removeConnection(q.agentic.user.id,q.params.id))return r.status(404).json({ok:false,error:"CONNECTION_NOT_FOUND"});r.json({ok:true})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/github/:id/repos",async(q,r)=>{try{r.json({ok:true,repositories:await application.github.repositories(q.agentic.user.id,q.params.id)})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/github/:id/branches/:owner/:repo",async(q,r)=>{try{r.json({ok:true,branches:await application.github.branches(q.agentic.user.id,q.params.id,q.params.owner,q.params.repo)})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/github/:id/tree/:owner/:repo",async(q,r)=>{try{r.json({ok:true,tree:await application.github.tree(q.agentic.user.id,q.params.id,q.params.owner,q.params.repo,q.query.branch||null)})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/github/:id/file/:owner/:repo/*path",async(q,r)=>{try{r.json({ok:true,file:await application.github.file(q.agentic.user.id,q.params.id,q.params.owner,q.params.repo,q.params.path,q.query.ref||null)})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/workspaces",async(q,r)=>r.json({ok:true,workspaces:await application.listWorkspaces(q.agentic.user.id)}));
 app.post("/api/agentic/workspaces",async(q,r)=>{try{r.status(201).json({ok:true,workspace:await application.createWorkspace(q.agentic.user.id,q.body||{})})}catch(e){sendError(r,e)}});
 app.post("/api/agentic/chat",async(q,r)=>{try{r.json({ok:true,...await application.chat(q.agentic.user.id,q.body||{})})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/executions",async(q,r)=>r.json({ok:true,executions:await application.listExecutions(q.agentic.user.id)}));
 app.get("/api/agentic/executions/:id",async(q,r)=>{try{r.json({ok:true,execution:await application.getExecution(q.agentic.user.id,q.params.id)})}catch(e){sendError(r,e)}});
 app.post("/api/agentic/executions/:id/approve",async(q,r)=>{try{r.json({ok:true,...await application.approveExecution(q.agentic.user.id,q.params.id)})}catch(e){sendError(r,e)}});
 app.post("/api/agentic/executions/:id/cancel",async(q,r)=>{try{r.json({ok:true,execution:await application.cancelExecution(q.agentic.user.id,q.params.id)})}catch(e){sendError(r,e)}});
 app.get("/api/agentic/tasks",async(q,r)=>r.json({ok:true,tasks:await application.listTasks(q.agentic.user.id)}));
 app.get("/api/agentic/activity",async(q,r)=>r.json({ok:true,activity:await application.listActivities(q.agentic.user.id)}));
 app.use((q,r,n)=>{if(q.path.startsWith("/api/"))return n();return r.sendFile(path.join(root,"index.html"));});
 const port=Number(configuration.port||process.env.AGENTIC_PORT||3100),host=configuration.host||process.env.AGENTIC_HOST||"127.0.0.1";const server=app.listen(port,host);return {app,server,port,host,application};}
if(import.meta.url===`file://${process.argv[1]}`)createAgenticServer();
