import { AgenticError } from "./errors.js";
import { createId, assertId } from "./ids.js";

const STATES = Object.freeze(["draft","ready","running","waiting_approval","paused","completed","failed","cancelled","stopped"]);
const TERMINAL = new Set(["completed","failed","cancelled","stopped"]);
const text = (value, code, message, max=12000) => { const result=String(value ?? "").trim(); if (!result) throw new AgenticError(code,message); return result.slice(0,max); };
function publicWork(work){return {id:work.id,ownerId:work.ownerId,projectId:work.projectId||null,workspaceId:work.workspaceId||null,objective:work.objective,context:work.context||{},plan:work.plan||null,taskIds:[...(work.taskIds||[])],executionIds:[...(work.executionIds||[])],changeIds:[...(work.changeIds||[])],evidenceIds:[...(work.evidenceIds||[])],approvalIds:[...(work.approvalIds||[])],result:work.result||null,state:work.state,priority:work.priority,createdAt:work.createdAt,updatedAt:work.updatedAt,startedAt:work.startedAt||null,finishedAt:work.finishedAt||null,cancelledAt:work.cancelledAt||null};}
export function createWorkService({store,tasks=null,executions=null}={}){
 if(!store?.putWork||!store?.getWork||!store?.listWorks) throw new TypeError("Work service membutuhkan store work contract");
 async function raw(ownerId,id){assertId(ownerId,"ownerId");assertId(id,"workId");const work=await store.getWork(ownerId,id);if(!work)throw new AgenticError("WORK_NOT_FOUND","Work tidak ditemukan",404);return work;}
 async function get(ownerId,id){return publicWork(await raw(ownerId,id));}
 async function list(ownerId,options={}){let works=await store.listWorks(ownerId);if(options.state)works=works.filter(work=>work.state===options.state);if(options.projectId!=null)works=works.filter(work=>work.projectId===options.projectId);if(options.workspaceId!=null)works=works.filter(work=>work.workspaceId===options.workspaceId);return works.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(publicWork);}
 async function create(ownerId,input={}){const objective=text(input.objective,"INVALID_WORK_OBJECTIVE","Work objective wajib diisi");const now=new Date().toISOString();const work={id:input.id||createId("work"),ownerId,projectId:input.projectId?assertId(input.projectId,"projectId"):null,workspaceId:input.workspaceId?assertId(input.workspaceId,"workspaceId"):null,objective,context:input.context&&typeof input.context==="object"?input.context:{},plan:null,taskIds:[],executionIds:[],changeIds:[],evidenceIds:[],approvalIds:[],result:null,state:"draft",priority:["low","normal","high","urgent"].includes(input.priority)?input.priority:"normal",createdAt:now,updatedAt:now,startedAt:null,finishedAt:null,cancelledAt:null};await store.putWork(ownerId,work,{overwrite:false});return publicWork(work);}
 async function update(ownerId,id,patch={}){const current=await raw(ownerId,id);if(TERMINAL.has(current.state))throw new AgenticError("WORK_TERMINAL","Work terminal tidak dapat diubah",409);const next={...current};if(patch.objective!==undefined)next.objective=text(patch.objective,"INVALID_WORK_OBJECTIVE","Work objective wajib diisi");if(patch.projectId!==undefined)next.projectId=patch.projectId?assertId(patch.projectId,"projectId"):null;if(patch.workspaceId!==undefined)next.workspaceId=patch.workspaceId?assertId(patch.workspaceId,"workspaceId"):null;if(patch.context!==undefined){if(!patch.context||typeof patch.context!=="object"||Array.isArray(patch.context))throw new AgenticError("INVALID_WORK_CONTEXT","Work context harus berupa object");next.context=patch.context;}if(patch.priority!==undefined){if(!["low","normal","high","urgent"].includes(patch.priority))throw new AgenticError("INVALID_WORK_PRIORITY","Priority work tidak valid");next.priority=patch.priority;}if(patch.plan!==undefined)next.plan=patch.plan;next.updatedAt=new Date().toISOString();await store.putWork(ownerId,next,{overwrite:true,expectedVersion:current._storage?.version});return publicWork(next);}
 async function reopenForRepair(ownerId,id,patch={}){const current=await raw(ownerId,id);if(current.state!=="failed")throw new AgenticError("WORK_NOT_REPAIRABLE","Hanya Work failed yang dapat dibuka kembali untuk repair",409);const now=new Date().toISOString();const next={...current,...patch,state:"ready",finishedAt:null,cancelledAt:null,updatedAt:now};await store.putWork(ownerId,next,{overwrite:true,expectedVersion:current._storage?.version});return publicWork(next);}
 async function transition(ownerId,id,state,meta={}){const current=await raw(ownerId,id);if(!STATES.includes(state))throw new AgenticError("INVALID_WORK_STATE","State work tidak valid");if(TERMINAL.has(current.state))throw new AgenticError("WORK_TERMINAL","Work terminal tidak dapat ditransisikan",409);const allowed={draft:new Set(["ready","cancelled"]),ready:new Set(["running","cancelled"]),running:new Set(["waiting_approval","paused","completed","failed","cancelled","stopped"]),waiting_approval:new Set(["running","paused","cancelled","failed"]),paused:new Set(["ready","running","cancelled","stopped"])};if(!allowed[current.state]?.has(state))throw new AgenticError("INVALID_WORK_TRANSITION",`Transisi work ${current.state} -> ${state} tidak diizinkan`,409);const now=new Date().toISOString();const next={...current,state,updatedAt:now};if(state==="running"&&!next.startedAt)next.startedAt=now;if(TERMINAL.has(state)){next.finishedAt=now;if(state==="cancelled")next.cancelledAt=now;if(meta.result!==undefined)next.result=meta.result;else if(meta.error)next.result={error:String(meta.error)};}if(meta.result!==undefined)next.result=meta.result;await store.putWork(ownerId,next,{overwrite:true,expectedVersion:current._storage?.version});return publicWork(next);}
 async function cancel(ownerId,id,reason="Work dibatalkan oleh user"){return transition(ownerId,id,"cancelled",{result:{status:"cancelled",reason:String(reason).slice(0,2000)}});}
 async function attachTask(ownerId,workId,taskId){assertId(taskId,"taskId");const current=await raw(ownerId,workId);if(tasks?.get)await tasks.get(ownerId,taskId);if(current.taskIds.includes(taskId))return publicWork(current);const next={...current,taskIds:[...current.taskIds,taskId],updatedAt:new Date().toISOString()};await store.putWork(ownerId,next,{overwrite:true,expectedVersion:current._storage?.version});return publicWork(next);}
 async function attachExecution(ownerId,workId,executionId){assertId(executionId,"executionId");const current=await raw(ownerId,workId);if(executions?.get)await executions.get(ownerId,executionId);if(current.executionIds.includes(executionId))return publicWork(current);const next={...current,executionIds:[...current.executionIds,executionId],updatedAt:new Date().toISOString()};await store.putWork(ownerId,next,{overwrite:true,expectedVersion:current._storage?.version});return publicWork(next);}
 async function attachReference(ownerId,workId,kind,id){const fields={change:"changeIds",evidence:"evidenceIds",approval:"approvalIds"};const field=fields[kind];if(!field)throw new AgenticError("INVALID_WORK_REFERENCE","Jenis reference work tidak valid");assertId(id,`${kind}Id`);const current=await raw(ownerId,workId);if(current[field].includes(id))return publicWork(current);const next={...current,[field]:[...current[field],id],updatedAt:new Date().toISOString()};await store.putWork(ownerId,next,{overwrite:true,expectedVersion:current._storage?.version});return publicWork(next);}
 return Object.freeze({states:STATES,terminalStates:Object.freeze([...TERMINAL]),raw,get,list,create,update,transition,reopenForRepair,cancel,attachTask,attachExecution,attachReference});
}
